### ISSUE TITLE
Artifact BOM

### ISSUE THREAD

**Issue by realdadfish** [RBusarow/Dispatch#219]
I just found your useful project here and figured that because of the number of artifacts it provides it might be useful to provide a BOM (bill of material) that lists all versions of all artifacts in a central place.

Such a thing could then be consumed in a [Gradle multi project build](https://docs.gradle.org/current/userguide/multi_project_builds.html) through

```kotlin
// my.platform.project:production
plugins {
    id("java-platform")
}

dependencies {
    api(platform("com.rickbusarow.dispatch:dispatch-bom:1.0.0-beta09"))
}
```

and this could be referenced in individual module files like so:

```kotlin
dependencies {
    implementation(platform("my.platform.project:production"))

    implementation("com.rickbusarow.dispatch:dispatch-core")
}
```

Creating and publishing such a BOM should be fairly easy. Thanks!

**Comment by RBusarow** [comment]
Hey, thanks for the reminder!  I agree this would be a good idea.  I've intended to do this for months, but it's been easy to ignore since no one has actually asked for it.

I should be able to get this done tonight.

**Comment by realdadfish** [comment]
Awesome, thank you!
