### ISSUE TITLE
junit-vintage-engine as runtimeOnly dependency

### ISSUE THREAD

**Issue by realdadfish** [RBusarow/Dispatch#231]
I discovered some quirks in my setup when I added the `dispatch-test` artifact to my test classpath. This artifact transitively pulls `org.junit.vintage:junit-vintage-engine` into the test compile classpath, which - [by documentation](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-engines-configure) - should only reside in the test runtime's classpath (i.e. `testRuntimeOnly`). The quirk now was that when I added `dispatch-test`, my tests were executed as wanted (as the JUnit4 runtime was on the classpath), but as soon as I removed it, tests weren't executed anymore.

The solution for me was obviously to depend on `junit-vintage-engine` myself, but I thought it might be a good idea to get rid of it in the transitive classpath as well.

**Comment by RBusarow** [comment]
Thanks for the report!  I'll get this fixed tonight.
